"""
Состояния FSM (хранятся в памяти по user_id, см. handlers/common.py).
У MAX Bot API нет встроенного FSM, поэтому реализуем простой словарь.
Значения состояний совпадают с именами констант, чтобы префиксная
маршрутизация в handlers/common.py (startswith) работала корректно.
"""

# Профиль (имя не собираем — только телефон)
PROFILE_WAIT_PHONE = "PROFILE_WAIT_PHONE"

# Запись
BOOKING_WAIT_SERVICE = "BOOKING_WAIT_SERVICE"
BOOKING_WAIT_MASTER = "BOOKING_WAIT_MASTER"
BOOKING_WAIT_DATE = "BOOKING_WAIT_DATE"
BOOKING_WAIT_HOUR = "BOOKING_WAIT_HOUR"
BOOKING_WAIT_MINUTE = "BOOKING_WAIT_MINUTE"
BOOKING_WAIT_CONFIRM = "BOOKING_WAIT_CONFIRM"

# Админка: услуги
ADMIN_SVC_ADD_NAME = "ADMIN_SVC_ADD_NAME"
ADMIN_SVC_ADD_DESC = "ADMIN_SVC_ADD_DESC"
ADMIN_SVC_ADD_PRICE = "ADMIN_SVC_ADD_PRICE"
ADMIN_SVC_ADD_DURATION = "ADMIN_SVC_ADD_DURATION"
ADMIN_SVC_EDIT_NAME = "ADMIN_SVC_EDIT_NAME"
ADMIN_SVC_EDIT_DESC = "ADMIN_SVC_EDIT_DESC"
ADMIN_SVC_EDIT_PRICE = "ADMIN_SVC_EDIT_PRICE"
ADMIN_SVC_EDIT_DURATION = "ADMIN_SVC_EDIT_DURATION"

# Админка: мастера
ADMIN_MASTER_ADD_NAME = "ADMIN_MASTER_ADD_NAME"
ADMIN_MASTER_ADD_SPEC = "ADMIN_MASTER_ADD_SPEC"
ADMIN_MASTER_EDIT_NAME = "ADMIN_MASTER_EDIT_NAME"
ADMIN_MASTER_EDIT_SPEC = "ADMIN_MASTER_EDIT_SPEC"
